services:
  - type: web
    name: vinted-scraper-api
    env: python
    buildCommand: pip install -r requirements.txt && python setup.py
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0